// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiNative;

#nullable disable

namespace WebApiNative.Infraestructure.Migrations
{
    [DbContext(typeof(NativeDBContext))]
    [Migration("20240517052843_initial ")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiNative.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CantidadInicial")
                        .HasColumnType("bigint");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("515212b7-307b-4298-b523-3b1a4854b883"),
                            CantidadInicial = 100L,
                            Categoria = "Ropa Interior",
                            Descripcion = "Media Azul",
                            Estado = true,
                            Nombre = "Medias",
                            Precio = 12.800000000000001
                        },
                        new
                        {
                            Id = new Guid("51989dcb-5ec8-4eb6-8bc2-cd3bf503fcc5"),
                            CantidadInicial = 100L,
                            Categoria = "Ropa Interior",
                            Descripcion = "Media Roja",
                            Estado = true,
                            Nombre = "Medias veladas",
                            Precio = 12.800000000000001
                        },
                        new
                        {
                            Id = new Guid("05eb8ba9-baaf-4609-bb2b-2361fcca807e"),
                            CantidadInicial = 100L,
                            Categoria = "Prendas Superiores",
                            Descripcion = "Tipo militar",
                            Estado = true,
                            Nombre = "Jeans Cargo",
                            Precio = 120.0
                        },
                        new
                        {
                            Id = new Guid("60681aa2-b0e6-4527-b866-911f4b3d52f1"),
                            CantidadInicial = 1000L,
                            Categoria = "Prendas Superiores",
                            Descripcion = "Unisex",
                            Estado = true,
                            Nombre = "Jeans Oversized",
                            Precio = 120.0
                        },
                        new
                        {
                            Id = new Guid("1ddfd9b6-3985-4422-8b64-c8d1a22004be"),
                            CantidadInicial = 1000L,
                            Categoria = "Prendas Superiores",
                            Descripcion = "FaldaShort Azul",
                            Estado = true,
                            Nombre = "FaldaShort",
                            Precio = 30.0
                        },
                        new
                        {
                            Id = new Guid("88a91de1-8a29-4426-8d69-a5d54dfa4482"),
                            CantidadInicial = 1000L,
                            Categoria = "Prenda Liviana",
                            Descripcion = "Vestido Azul",
                            Estado = true,
                            Nombre = "Vestido",
                            Precio = 50.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
